theme: jekyll-theme-minimal
title: Jessy Yang
description: |
  Master of Public Health (MPH), *Epidemiology and Biostatistics* 
  Boston University School of Public Health
show_downloads: false
google_analytics: G-FHE55JD0YL
